import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Theme, Container, ThemePanel } from "@radix-ui/themes";
import '@radix-ui/themes/styles.css';
import { AppProvider } from "@/context/appContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme accentColor="crimson" grayColor="sand" radius="large" scaling="95%">
          <Container><AppProvider >
            {children}</AppProvider></Container>
        </Theme>
      </body>
    </html>
  );
}
